{% set name = "gotranx" %}
{% set version = "1.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 31b2c105c660fc8d10bc469c4867446ff91efac57e7d972d941e5bac0be19458

build:
  number: 0
  noarch: python
  entry_points:
    - "gotranx=gotranx.cli:app"
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - attrs
    - lark
    - pint
    - rich-click
    - structlog
    - sympy
    - typer
    - toml
    - myokit
    - pandoc
test:
  requires:
    - python {{ python_min }}

  imports:
    - gotranx

  commands:
    - gotranx --help


about:
  home: https://github.com/finsberg/gotranx
  summary: A declarative language describing ordinary differential equations
  license: MIT
  license_file: LICENSE
  doc_url: https://finsberg.github.io/gotranx/
  dev_url: https://github.com/finsberg/gotranx

extra:
  recipe-maintainers:
    - finsberg
